---
title: "Assignment1"
author: "Kristin Gmunder"
date: "1/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Chapter 2: Data Structures



####Exercises 1

**1. What are the six types of atomic vector? How does a list differ from an atomic vector?**
The six types are: logical, integer, double, character, complex, and raw.  A list can have
elements of any type, even other lists.  An atomic vector has all the same type of elements.

**2. What makes is.vector() and is.numeric() fundamentally different to is.list() and is.character()?**
is.vector() and is.numeric() are not very good tests of structure.  is.vector() returns 
TRUE only if the object is a vector with no attributes apart from names and 
is.numeric() returns TRUE for both integer and double vectors.  Whereas, is.list() and is.character() are useful and accurate for determining structure.

**3. Test your knowledge of vector coercion rules by predicting the output of the following uses of c():**

c(1, FALSE)
The output is 1 0, because the logical is coerced to a double (less flexible is converted to more
flexible).

c("a", 1)
The output is "a" "1", because the double is coerced to a character.

c(list(1), "a")
The output is a list of 1 and "a", because the c() causes the list of size one to be combined
into a singular list.

c(TRUE, 1L)
The output is 1 1, because the logical is coerced to an integer.

**4. Why do you need to use unlist() to convert a list to an atomic vector? Why doesn’t as.vector() work?**
Since lists are already vectors (non-atomic vectors), nothing will happen to a list when as.vector() is used.

**5. Why is 1 == "1" true? Why is -1 < FALSE true? Why is "one" < 2 false?**
1 is coerced to "1" (less flexible is converted to more flexible).  FALSE is coerced to 1, so -1 < 1 is true.  2 is coerced to "2", but R cannot compare character strings.

**6. Why is the default missing value, NA, a logical vector? What’s special about logical vectors? (Hint: think about c(FALSE, NA_character_).)**
Logical data type is the least flexible data type, so it is often coerced to more flexible data types.  In c(FALSE, NA_character_), FALSE (a logical) is coerced to a character, because this NA
is of character type.





####Exercises 2

**1. An early draft used this code to illustrate structure():**
structure(1:5, comment = "my attribute")
## [1] 1 2 3 4 5
**But when you print that object you don’t see the comment attribute. Why? Is the attribute missing, or is there something else special about it? (Hint: try using help.)**
According to the help file, a comment attribute is not printed, unlike other attributes.

**2. What happens to a factor when you modify its levels?**
f1 <- factor(letters)
levels(f1) <- rev(levels(f1))
The order of the factor changed with the levels changing.

**3. What does this code do? How do f2 and f3 differ from f1?**
f2 <- rev(factor(letters))
f3 <- factor(letters, levels = rev(letters))
The code reverses the order of the factor, but keeps the levels like original letters in f2.
The code reverses the order of the levels, but keeps the factors like original letters in f3.
f2 is the same factor as f1, but reversed levels.  f3 is a different order of factors, but the 
same order of levels.




####Exercises 3

**1. What does dim() return when applied to a vector?**
dim() returns NULL when applied to a vector, because a vector only has one dimension, 
thus dim cannot handle this.

**2. If is.matrix(x) is TRUE, what will is.array(x) return?**
is.array(x) will return TRUE, because a matrix is just a two-dimensional array.

**3. How would you describe the following three objects? What makes them different to 1:5?**
x1 <- array(1:5, c(1, 1, 5))
This is a 1x1x5 array of the numbers 1 to 5.

x2 <- array(1:5, c(1, 5, 1))
This is a 1x5x1 array of the numbers 1 to 5.

x3 <- array(1:5, c(5, 1, 1))
This is a 5x1x1 array of the numbers 1 to 5.

Whereas, 1:5 is a vector of length 5 with the numbers 1 to 5.





####Exercises 4

**1. What attributes does a data frame possess?**
A data frame has names, row.names, class, and can also have comment.

**2. What does as.matrix() do when applied to a data frame with columns of different types?**
as.matrix() will coerce elements to the most flexible data type in the data frame, so that
way all the columns will be of the same type.

**3. Can you have a data frame with 0 rows? What about 0 columns?**
Yes, the data frame can have 0 rows and 0 columns, it would be empty.