---
title: "Assignment7"
author: "Kristin Gmunder"
date: "3/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Question 1**  
For $\lambda = 2$, plot gamma distribution for a few values of $\alpha$:
```{r}
gamma_fun <- function(lambda, alpha, x) {
  ((lambda^alpha)/factorial(alpha-1))*(x^(alpha-1)*exp(-lambda*x))
}

plot(seq(1:100), gamma_fun(2, 1, seq(1:100)))
plot(seq(1:100), gamma_fun(2, 2, seq(1:100)))
plot(seq(1:100), gamma_fun(2, 3, seq(1:100)))
plot(seq(1:100), gamma_fun(2, 4, seq(1:100)))
plot(seq(1:100), gamma_fun(2, 5, seq(1:100)))
```

**Question 2**  
For $\lambda = 1$, plot chi-squared distribution for a few values of $\alpha$:
```{r}
chi_fun <- function(lambda, alpha, x) {
  (1/(factorial(alpha-1)*2^alpha))*(x^(alpha-1)*exp(-x/2))
}

plot(seq(1:100), chi_fun(1, 1, seq(1:100)))
plot(seq(1:100), chi_fun(1, 2, seq(1:100)))
plot(seq(1:100), chi_fun(1, 3, seq(1:100)))
plot(seq(1:100), chi_fun(1, 4, seq(1:100)))
plot(seq(1:100), chi_fun(1, 5, seq(1:100)))
```


